# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Provider',
        ),
    ]
