# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_auto_20160622_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='currency',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='language',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='phonenum',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
