# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_auto_20160622_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polygon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('latitude', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
                ('pub_date', models.DateField(null=True)),
                ('mod_date', models.DateField(null=True)),
                ('n_comments', models.IntegerField(default=0)),
                ('n_pingbacks', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
                ('authors', models.ManyToManyField(to='example.Provider')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='example.Blog')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='entry',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='blog',
        ),
        migrations.AlterField(
            model_name='comment',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='example.Polygon'),
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
